/**
 * Catálogo de cidades, vilas e freguesias icónicas de Portugal.
 * ~300 entradas — cobertura nacional incluindo arquipélagos e
 * algumas freguesias culturalmente reconhecidas (Alfama, Belém, Foz, …).
 *
 * Cada entrada tem:
 *   id           slug ASCII estável (chave única)
 *   name         nome PT-PT com diacríticos correctos
 *   district     distrito ou região autónoma
 *   region       Norte | Centro | Lisboa | Alentejo | Algarve | Madeira | Açores
 *   nickname     alcunha cultural ("Cidade Invicta", "Princesa do Lima"…)
 *   description  uma linha autêntica — história, cultura, tradição, gastronomia
 *
 * A redação é PT-PT (ortografia 1945 sempre que faça diferença para o leitor),
 * com tom literário curto. Sem clichés genéricos.
 */

export const PT_REGIONS = [
    { key: "norte",     label: "Norte" },
    { key: "centro",    label: "Centro" },
    { key: "lisboa",    label: "Lisboa" },
    { key: "alentejo",  label: "Alentejo" },
    { key: "algarve",   label: "Algarve" },
    { key: "madeira",   label: "Madeira" },
    { key: "acores",    label: "Açores" },
];

export const PT_CITIES = [
    // ─── DISTRITO DE AVEIRO ────────────────────────────────────────────────
    { id: "aveiro",            name: "Aveiro",              district: "Aveiro",    region: "centro",
      nickname: "A Veneza de Portugal",
      description: "Moliceiros, ovos-moles e canais salgados; cidade do sal, da Universidade e da Arte Nova." },
    { id: "agueda",            name: "Águeda",              district: "Aveiro",    region: "centro",
      nickname: "A vila dos guarda-chuvas",
      description: "Rua coberta por chapéus suspensos no AgitÁgueda — arte urbana feita verão." },
    { id: "albergaria-a-velha", name: "Albergaria-a-Velha",  district: "Aveiro",    region: "centro",
      nickname: "Encruzilhada do Vouga",
      description: "Antigo pouso de peregrinos a caminho de Santiago, hoje portão da Bairrada." },
    { id: "anadia",            name: "Anadia",              district: "Aveiro",    region: "centro",
      nickname: "Capital do espumante",
      description: "Coração da Bairrada — leitão à Mealhada, baga e adegas centenárias." },
    { id: "arouca",            name: "Arouca",              district: "Aveiro",    region: "norte",
      nickname: "Reino das Trilobites",
      description: "Geoparque mundial UNESCO; convento, Paiva Walkways e a ponte 516." },
    { id: "espinho",           name: "Espinho",             district: "Aveiro",    region: "norte",
      nickname: "A cidade-quadrícula",
      description: "Praia ordenada à régua, casino e Feira Semanal — o domingo do Norte." },
    { id: "estarreja",         name: "Estarreja",           district: "Aveiro",    region: "centro",
      nickname: "Sentinela da Ria",
      description: "BioRia, Carnaval e indústria química — onde a natureza e a fábrica convivem." },
    { id: "ilhavo",            name: "Ílhavo",              district: "Aveiro",    region: "centro",
      nickname: "Terra do bacalhau",
      description: "Museu Marítimo, Vista Alegre e a saga dos navios para a Terra Nova." },
    { id: "mealhada",          name: "Mealhada",            district: "Aveiro",    region: "centro",
      nickname: "Capital do leitão",
      description: "Leitão à Mealhada, vinho da Bairrada e a Mata do Buçaco à mão." },
    { id: "oliveira-de-azemeis", name: "Oliveira de Azeméis", district: "Aveiro",   region: "norte",
      nickname: "A cidade do Caima",
      description: "Indústria, papel e a Casa-Museu de Ferreira de Castro — terra de escritores." },
    { id: "ovar",              name: "Ovar",                district: "Aveiro",    region: "norte",
      nickname: "Capital do Carnaval do Norte",
      description: "Pão-de-ló húmido, azulejos nas fachadas e três dias de loucura em Fevereiro." },
    { id: "sao-joao-da-madeira", name: "São João da Madeira", district: "Aveiro",   region: "norte",
      nickname: "Capital do calçado",
      description: "O concelho mais pequeno do país — chapéus, lápis e sapatos exportados ao mundo." },
    { id: "santa-maria-da-feira", name: "Santa Maria da Feira", district: "Aveiro", region: "norte",
      nickname: "Cidade-castelo",
      description: "Viagem Medieval no Verão, Fogaça e o castelo das oito torres." },
    { id: "vagos",             name: "Vagos",               district: "Aveiro",    region: "centro",
      nickname: "Praia do Vagueira",
      description: "Floresta, dunas e o festival metal mais alto da Península." },
    { id: "vale-de-cambra",    name: "Vale de Cambra",      district: "Aveiro",    region: "norte",
      nickname: "Berço da Serra da Freita",
      description: "Pedras Parideiras, rota dos lagares e queijo de cabra serrano." },

    // ─── DISTRITO DE BEJA ──────────────────────────────────────────────────
    { id: "beja",              name: "Beja",                district: "Beja",      region: "alentejo",
      nickname: "Cidade da rainha Santa",
      description: "Cante alentejano, castelo branco no horizonte e o pão dos campos infinitos." },
    { id: "aljustrel",         name: "Aljustrel",           district: "Beja",      region: "alentejo",
      nickname: "Vila mineira",
      description: "Cobre romano, sindicalismo operário e a planície ardente do Baixo Alentejo." },
    { id: "almodovar",         name: "Almodôvar",           district: "Beja",      region: "alentejo",
      nickname: "Encruzilhada do Sul",
      description: "Escrita do sudoeste, queijo de cabra e o silêncio da Serra do Caldeirão." },
    { id: "barrancos",         name: "Barrancos",           district: "Beja",      region: "alentejo",
      nickname: "Fronteira do barranquenho",
      description: "Onde se fala um português mesclado de castelhano — presunto pata negra ibérico." },
    { id: "castro-verde",      name: "Castro Verde",        district: "Beja",      region: "alentejo",
      nickname: "Capital do Cante",
      description: "Estepe cerealífera, abetardas e património imaterial UNESCO em cada arruada." },
    { id: "cuba",              name: "Cuba",                district: "Beja",      region: "alentejo",
      nickname: "A vila de Colombo (talvez)",
      description: "Reclama o navegador como filho — vinho do Alentejo e azinheiras seculares." },
    { id: "ferreira-do-alentejo", name: "Ferreira do Alentejo", district: "Beja",   region: "alentejo",
      nickname: "Capital do azeite",
      description: "Olival intensivo, lagares modernos e o sol-posto sobre o Alqueva." },
    { id: "mertola",           name: "Mértola",             district: "Beja",      region: "alentejo",
      nickname: "Vila-museu mourisca",
      description: "Castelo no Guadiana, mesquita-igreja e o império romano em estratos." },
    { id: "moura",             name: "Moura",               district: "Beja",      region: "alentejo",
      nickname: "Vila da moura encantada",
      description: "Mouraria intacta, azeite premiado e a lenda da donzela que se atirou da torre." },
    { id: "odemira",           name: "Odemira",             district: "Beja",      region: "alentejo",
      nickname: "O maior concelho do país",
      description: "Costa Vicentina, Mira, Zambujeira do Mar — natureza protegida sem fim." },
    { id: "ourique",           name: "Ourique",             district: "Beja",      region: "alentejo",
      nickname: "Berço de Portugal",
      description: "Batalha mítica de 1139, porco preto e o Cante que ainda se canta à mesa." },
    { id: "serpa",             name: "Serpa",               district: "Beja",      region: "alentejo",
      nickname: "Cidade-queijo",
      description: "Queijo amanteigado, muralhas restauradas e o relógio mais antigo de Portugal." },
    { id: "vidigueira",        name: "Vidigueira",          district: "Beja",      region: "alentejo",
      nickname: "Terra de Vasco da Gama",
      description: "Vinho talha, sepultura do navegador e a planície dourada de Setembro." },

    // ─── DISTRITO DE BRAGA ─────────────────────────────────────────────────
    { id: "braga",             name: "Braga",               district: "Braga",     region: "norte",
      nickname: "Roma Portuguesa",
      description: "Bracara Augusta, arquidiocese primaz e a cidade jovem mais católica do país." },
    { id: "amares",            name: "Amares",              district: "Braga",     region: "norte",
      nickname: "Vila do Vinho Verde",
      description: "Termas do Caldelas, mosteiro de Bouro e a serra do Gerês em pano de fundo." },
    { id: "barcelos",          name: "Barcelos",            district: "Braga",     region: "norte",
      nickname: "Vila do Galo",
      description: "Galo de barro, feira semanal e olaria que conquistou o mundo." },
    { id: "cabeceiras-de-basto", name: "Cabeceiras de Basto", district: "Braga",   region: "norte",
      nickname: "Terra de Basto",
      description: "Estátuas dos cavaleiros, mosteiro de Refojos e bordados centenários." },
    { id: "celorico-de-basto", name: "Celorico de Basto",   district: "Braga",     region: "norte",
      nickname: "Vila dos solares",
      description: "Casas brasonadas, vinho verde e o Tâmega a serpentear." },
    { id: "esposende",         name: "Esposende",           district: "Braga",     region: "norte",
      nickname: "A cidade do Cávado",
      description: "Foz do rio, dunas de Apúlia e moinhos de Forjães rendados ao vento." },
    { id: "fafe",              name: "Fafe",                district: "Braga",     region: "norte",
      nickname: "A vila das casas dos brasileiros",
      description: "Arquitectura de torna-viagem, terra de Vasco da Gama Fernandes." },
    { id: "guimaraes",         name: "Guimarães",           district: "Braga",     region: "norte",
      nickname: "Berço da Nação",
      description: "Aqui nasceu Portugal — castelo de D. Afonso Henriques, centro histórico UNESCO." },
    { id: "povoa-de-lanhoso",  name: "Póvoa de Lanhoso",    district: "Braga",     region: "norte",
      nickname: "Terra da filigrana",
      description: "Coração mais alto do mundo, ourivesaria em fio de ouro e o castelo no monte." },
    { id: "terras-de-bouro",   name: "Terras de Bouro",     district: "Braga",     region: "norte",
      nickname: "Porta do Gerês",
      description: "Vilarinho da Furna submersa, geira romana e o lobo ibérico nas serras." },
    { id: "vieira-do-minho",   name: "Vieira do Minho",     district: "Braga",     region: "norte",
      nickname: "Terra de bordados",
      description: "Vilarinho da Furna, granito e o linho cru das bordadeiras do Minho." },
    { id: "vila-nova-de-famalicao", name: "Vila Nova de Famalicão", district: "Braga", region: "norte",
      nickname: "A cidade têxtil",
      description: "Casa de Camilo Castelo Branco, indústria do Vale do Ave em metamorfose." },
    { id: "vila-verde",        name: "Vila Verde",          district: "Braga",     region: "norte",
      nickname: "Terra dos lenços dos namorados",
      description: "Bordados de amor com erros propositados — declaração em linho." },
    { id: "vizela",            name: "Vizela",              district: "Braga",     region: "norte",
      nickname: "Cidade termal",
      description: "Águas sulfurosas, romaria de S. Bento das Peras e o concelho mais novo do país." },

    // ─── DISTRITO DE BRAGANÇA ──────────────────────────────────────────────
    { id: "braganca",          name: "Bragança",            district: "Bragança",  region: "norte",
      nickname: "Cidade-rainha do Nordeste",
      description: "Castelo, Domus Municipalis e a casa que deu rainhas a meia Europa." },
    { id: "alfandega-da-fe",   name: "Alfândega da Fé",     district: "Bragança",  region: "norte",
      nickname: "A vila das cerejas",
      description: "Cerejeiras em flor na primavera, amêndoa, azeite e o silêncio do planalto." },
    { id: "carrazeda-de-ansiaes", name: "Carrazeda de Ansiães", district: "Bragança", region: "norte",
      nickname: "Sentinela do Douro",
      description: "Maçã, castelo de Ansiães em ruínas dramáticas e o vinho do Douro Superior." },
    { id: "freixo-de-espada-a-cinta", name: "Freixo de Espada à Cinta", district: "Bragança", region: "norte",
      nickname: "Berço de Jorge Álvares",
      description: "Amendoeiras, seda histórica e o primeiro português a chegar à China." },
    { id: "macedo-de-cavaleiros", name: "Macedo de Cavaleiros", district: "Bragança", region: "norte",
      nickname: "Coração transmontano",
      description: "Albufeira do Azibo, alheira premiada e a Festa do Butelo no Inverno." },
    { id: "miranda-do-douro",  name: "Miranda do Douro",    district: "Bragança",  region: "norte",
      nickname: "Cidade dos Pauliteiros",
      description: "Língua mirandesa oficial, dança guerreira e o desfiladeiro do Douro Internacional." },
    { id: "mirandela",         name: "Mirandela",           district: "Bragança",  region: "norte",
      nickname: "Capital da alheira",
      description: "Alheira de caça, mil pontes sobre o Tua e o presunto de Vinhais à mesa." },
    { id: "mogadouro",         name: "Mogadouro",           district: "Bragança",  region: "norte",
      nickname: "Terra dos Templários",
      description: "Castelo templário, planalto frio e o butelo das matanças de Dezembro." },
    { id: "torre-de-moncorvo", name: "Torre de Moncorvo",   district: "Bragança",  region: "norte",
      nickname: "Vila da amêndoa",
      description: "Amendoais em flor, ferro do Reboredo e o casario debruçado sobre o Douro." },
    { id: "vimioso",           name: "Vimioso",             district: "Bragança",  region: "norte",
      nickname: "Terra do touro de morte",
      description: "Tourada à corda, lhambo mirandês e os campos altos do Nordeste." },
    { id: "vinhais",           name: "Vinhais",             district: "Bragança",  region: "norte",
      nickname: "Capital do fumeiro",
      description: "Feira do fumeiro em Fevereiro, presunto premiado e a Serra da Coroa." },

    // ─── DISTRITO DE CASTELO BRANCO ────────────────────────────────────────
    { id: "castelo-branco",    name: "Castelo Branco",      district: "Castelo Branco", region: "centro",
      nickname: "Cidade das colchas bordadas",
      description: "Jardim do Paço, bordados de seda e linho, capital da Beira Baixa." },
    { id: "belmonte",          name: "Belmonte",            district: "Castelo Branco", region: "centro",
      nickname: "Berço de Pedro Álvares Cabral",
      description: "Castelo do navegador, comunidade judaica viva e Sinagoga restaurada." },
    { id: "covilha",           name: "Covilhã",             district: "Castelo Branco", region: "centro",
      nickname: "Cidade-fábrica da Estrela",
      description: "Burel, lã, universidade e o teleférico para a montanha mais alta." },
    { id: "fundao",            name: "Fundão",              district: "Castelo Branco", region: "centro",
      nickname: "Capital da cereja",
      description: "Aldeias do Xisto, cerejeiras em flor e o festival Cherryx na primavera." },
    { id: "idanha-a-nova",     name: "Idanha-a-Nova",       district: "Castelo Branco", region: "centro",
      nickname: "Cidade Criativa UNESCO da Música",
      description: "Boom Festival no Verão, Monsanto pétreo e a aldeia mais portuguesa." },
    { id: "oleiros",           name: "Oleiros",             district: "Castelo Branco", region: "centro",
      nickname: "Aldeias do Xisto",
      description: "Esquecida e bela — caça grossa, mel da Beira e penhascos do Zêzere." },
    { id: "penamacor",         name: "Penamacor",           district: "Castelo Branco", region: "centro",
      nickname: "Sentinela da Raia",
      description: "Castelo defensivo, lobo-ibérico, abetarda — vila do silêncio." },
    { id: "proenca-a-nova",    name: "Proença-a-Nova",      district: "Castelo Branco", region: "centro",
      nickname: "Vila das aldeias do xisto",
      description: "Floresta e xisto, praias fluviais e o céu mais limpo da Beira." },
    { id: "sertã",             name: "Sertã",               district: "Castelo Branco", region: "centro",
      nickname: "Vila do maranho",
      description: "Maranho enrolado em folha de couve, bucho recheado e merendas de pastor." },
    { id: "vila-de-rei",       name: "Vila de Rei",         district: "Castelo Branco", region: "centro",
      nickname: "Centro geodésico de Portugal",
      description: "Picoto da Melriça — o coração geométrico do país marcado em pedra." },
    { id: "vila-velha-de-rodao", name: "Vila Velha de Ródão", district: "Castelo Branco", region: "centro",
      nickname: "Portas do Ródão",
      description: "Garganta do Tejo, gravuras paleolíticas e abutres a planar sobre o desfiladeiro." },

    // ─── DISTRITO DE COIMBRA ───────────────────────────────────────────────
    { id: "coimbra",           name: "Coimbra",             district: "Coimbra",   region: "centro",
      nickname: "Cidade dos estudantes",
      description: "Universidade do séc. XIII, fado, capa e batina — primeira capital do Reino." },
    { id: "arganil",           name: "Arganil",             district: "Coimbra",   region: "centro",
      nickname: "Capital do Pinhal",
      description: "Carlitos Branco, Serra do Açor e o vinho da encosta a brilhar." },
    { id: "cantanhede",        name: "Cantanhede",          district: "Coimbra",   region: "centro",
      nickname: "Terra do Lusitano",
      description: "Cavalos puros-sangues, Bairrada e a baga a fermentar nas adegas." },
    { id: "condeixa-a-nova",   name: "Condeixa-a-Nova",     district: "Coimbra",   region: "centro",
      nickname: "Junto a Conímbriga",
      description: "Maior cidade romana de Portugal mesmo ali — mosaicos, banhos, fórum." },
    { id: "figueira-da-foz",   name: "Figueira da Foz",     district: "Coimbra",   region: "centro",
      nickname: "Rainha das praias",
      description: "Casino, ondas para surf e a praia mais larga da Europa em maré-baixa." },
    { id: "gois",              name: "Góis",                district: "Coimbra",   region: "centro",
      nickname: "Vila do Ceira",
      description: "Praias fluviais, motas e o festival Gois Folk com nome internacional." },
    { id: "lousã",             name: "Lousã",               district: "Coimbra",   region: "centro",
      nickname: "Capital do Burel",
      description: "Aldeias do xisto, castelo no penedo e a Serra com veados a galopar." },
    { id: "mira",              name: "Mira",                district: "Coimbra",   region: "centro",
      nickname: "Vila piscatória das palheiros",
      description: "Praia, lagoa, casinhas de madeira riscadas — palheiros únicos no país." },
    { id: "miranda-do-corvo",  name: "Miranda do Corvo",    district: "Coimbra",   region: "centro",
      nickname: "Terra da Chanfana",
      description: "Cabra ao vinho tinto cozida em forno de lenha — receita da serra." },
    { id: "montemor-o-velho",  name: "Montemor-o-Velho",    district: "Coimbra",   region: "centro",
      nickname: "Castelo no arrozal",
      description: "Castelo medieval sobre a planície do Mondego, capital da remada." },
    { id: "oliveira-do-hospital", name: "Oliveira do Hospital", district: "Coimbra", region: "centro",
      nickname: "Terra de S. Marcos",
      description: "Ordem do Hospital, Serra da Estrela, queijo amanteigado e mel de urze." },
    { id: "penacova",          name: "Penacova",            district: "Coimbra",   region: "centro",
      nickname: "Princesa do Mondego",
      description: "Lampreia, ferrá, paisagem em torno do Penedo da Saudade." },
    { id: "penela",            name: "Penela",              district: "Coimbra",   region: "centro",
      nickname: "Aldeia Histórica do Centro",
      description: "Castelo templário, Presépio Monumental e a Villa Romana do Rabaçal." },
    { id: "soure",             name: "Soure",               district: "Coimbra",   region: "centro",
      nickname: "Terra Templária",
      description: "Castelo dado por Afonso Henriques aos Templários — anterior a Tomar." },
    { id: "tabua",             name: "Tábua",               district: "Coimbra",   region: "centro",
      nickname: "Cidade do bucho recheado",
      description: "Encruzilhada da Beira, Mondego a banhar e a Serra do Caramulo em vista." },

    // ─── DISTRITO DE ÉVORA ─────────────────────────────────────────────────
    { id: "evora",             name: "Évora",               district: "Évora",     region: "alentejo",
      nickname: "Cidade-museu UNESCO",
      description: "Templo romano, Capela dos Ossos, Universidade jesuíta — Alentejo central." },
    { id: "alandroal",         name: "Alandroal",           district: "Évora",     region: "alentejo",
      nickname: "Vila branca da raia",
      description: "Castelo medieval, mármores de Estremoz e o silêncio do Alqueva." },
    { id: "arraiolos",         name: "Arraiolos",           district: "Évora",     region: "alentejo",
      nickname: "Vila dos tapetes",
      description: "Tapetes de lã bordados há séculos — pontos contados que tecem histórias." },
    { id: "borba",             name: "Borba",               district: "Évora",     region: "alentejo",
      nickname: "Capital do mármore",
      description: "Pedreiras brancas, vinho tinto encorpado e a Festa da Vinha e do Vinho." },
    { id: "estremoz",          name: "Estremoz",            district: "Évora",     region: "alentejo",
      nickname: "Cidade branca do mármore",
      description: "Sábado de mercado, bonecos de barro patrimoniais, queijo e ameixa." },
    { id: "montemor-o-novo",   name: "Montemor-o-Novo",     district: "Évora",     region: "alentejo",
      nickname: "Berço de São João de Deus",
      description: "Castelo no monte, Pé-no-Chão e teatro experimental no Espaço do Tempo." },
    { id: "mora",              name: "Mora",                district: "Évora",     region: "alentejo",
      nickname: "Vila do Fluviário",
      description: "Único aquário de água doce do país, dólmens e azinheiras pelo horizonte." },
    { id: "mourao",            name: "Mourão",              district: "Évora",     region: "alentejo",
      nickname: "Capital da capa de Mourão",
      description: "Vila empoleirada sobre o Alqueva — caça, cante e mantas tradicionais." },
    { id: "portel",            name: "Portel",              district: "Évora",     region: "alentejo",
      nickname: "Vila do Sertão",
      description: "Castelo bem conservado, Alqueva em pano de fundo e queijo de ovelha." },
    { id: "redondo",           name: "Redondo",             district: "Évora",     region: "alentejo",
      nickname: "Vila dos olarios e do vinho",
      description: "Festa das Flores em rua coberta, cerâmica popular e vinho premiado." },
    { id: "reguengos-de-monsaraz", name: "Reguengos de Monsaraz", district: "Évora", region: "alentejo",
      nickname: "Capital do vinho do Alentejo",
      description: "Monsaraz medieval no alto, Alqueva azul, Mantelinha em Setembro." },
    { id: "vendas-novas",      name: "Vendas Novas",        district: "Évora",     region: "alentejo",
      nickname: "Capital da carne de porco à alentejana",
      description: "Encruzilhada do Alentejo, escola militar e a prova rainha do Sul." },
    { id: "viana-do-alentejo", name: "Viana do Alentejo",   district: "Évora",     region: "alentejo",
      nickname: "Vila da romaria a cavalo",
      description: "Romaria de Nossa Senhora d'Aires, castelo gótico-manuelino e cante." },
    { id: "vila-vicosa",       name: "Vila Viçosa",         district: "Évora",     region: "alentejo",
      nickname: "Princesa do Alentejo",
      description: "Paço Ducal dos Bragança, mármore e laranjeiras nas ruas brancas." },

    // ─── DISTRITO DE FARO (ALGARVE) ────────────────────────────────────────
    { id: "faro",              name: "Faro",                district: "Faro",      region: "algarve",
      nickname: "Capital da Ria Formosa",
      description: "Cidade Velha cercada de muralhas, sapais e ilhas de areia branca." },
    { id: "albufeira",         name: "Albufeira",           district: "Faro",      region: "algarve",
      nickname: "A morena da costa",
      description: "Falésias ocres, Praia dos Pescadores e a noite mais turística do Algarve." },
    { id: "alcoutim",          name: "Alcoutim",            district: "Faro",      region: "algarve",
      nickname: "Vila do Guadiana",
      description: "Vila gémea de Sanlúcar — tirolesa transfronteiriça entre os dois reinos." },
    { id: "aljezur",           name: "Aljezur",             district: "Faro",      region: "algarve",
      nickname: "Vila da batata-doce",
      description: "Costa Vicentina, surf, batata-doce com Denominação de Origem." },
    { id: "castro-marim",      name: "Castro Marim",        district: "Faro",      region: "algarve",
      nickname: "Vila do sal e da raia",
      description: "Reserva natural, sal artesanal e fortaleza com vista para Espanha." },
    { id: "lagoa",             name: "Lagoa",               district: "Faro",      region: "algarve",
      nickname: "Capital do moscatel algarvio",
      description: "Praias com grutas — Marinha e Benagil — e adegas brancas em redor." },
    { id: "lagos",             name: "Lagos",               district: "Faro",      region: "algarve",
      nickname: "Cidade dos Descobrimentos",
      description: "Henrique navegador partia daqui — Ponta da Piedade, Camilo, Dona Ana." },
    { id: "loule",             name: "Loulé",               district: "Faro",      region: "algarve",
      nickname: "Capital do Carnaval do Algarve",
      description: "Mercado oitocentista, lenços de seda e folar de Páscoa em forno de lenha." },
    { id: "monchique",         name: "Monchique",           district: "Faro",      region: "algarve",
      nickname: "Serra do medronho",
      description: "Caldas, água sulfurosa, medronho destilado e enchidos da serra." },
    { id: "olhao",             name: "Olhão",               district: "Faro",      region: "algarve",
      nickname: "Cidade do peixe",
      description: "Cubismo branco mediterrânico, mercado de ferro forjado e atum a fumar." },
    { id: "portimao",          name: "Portimão",            district: "Faro",      region: "algarve",
      nickname: "Cidade da sardinha assada",
      description: "Doca pesqueira, Praia da Rocha e o festival de sardinha em Agosto." },
    { id: "sao-bras-de-alportel", name: "São Brás de Alportel", district: "Faro",  region: "algarve",
      nickname: "Capital da cortiça",
      description: "Serra algarvia, museu do traje e o sobreiro descortiçado a cada nove anos." },
    { id: "silves",            name: "Silves",              district: "Faro",      region: "algarve",
      nickname: "Antiga capital mourisca",
      description: "Xelb dos árabes, castelo vermelho e festival medieval em Agosto." },
    { id: "tavira",            name: "Tavira",              district: "Faro",      region: "algarve",
      nickname: "A Veneza do Algarve",
      description: "37 igrejas, ponte romana e o sotavento mais sereno do reino." },
    { id: "vila-do-bispo",     name: "Vila do Bispo",       district: "Faro",      region: "algarve",
      nickname: "Sagres — o fim do mundo",
      description: "Cabo de São Vicente, escola de náutica de Henrique, ondas atlânticas." },
    { id: "vila-real-de-santo-antonio", name: "Vila Real de Santo António", district: "Faro", region: "algarve",
      nickname: "A cidade pombalina do Sul",
      description: "Traçado xadrez do Marquês, atum, areia branca e Espanha do outro lado." },

    // ─── DISTRITO DA GUARDA ────────────────────────────────────────────────
    { id: "guarda",            name: "Guarda",              district: "Guarda",    region: "centro",
      nickname: "A cidade mais alta de Portugal",
      description: "1056m, fria, forte, farta e fiel — os cinco Fs medievais da catedral granítica." },
    { id: "aguiar-da-beira",   name: "Aguiar da Beira",     district: "Guarda",    region: "centro",
      nickname: "Berço dos solares",
      description: "Casas brasonadas, igreja matriz românica e o pelourinho mais bonito da Beira." },
    { id: "almeida",           name: "Almeida",             district: "Guarda",    region: "centro",
      nickname: "Vila-estrela militar",
      description: "Fortaleza abaluartada em forma de hexagrama, raia, vinhos de granito." },
    { id: "celorico-da-beira", name: "Celorico da Beira",   district: "Guarda",    region: "centro",
      nickname: "Capital do Queijo da Serra",
      description: "Feira do queijo na Praça do Município, cardo selvagem e ovelha bordaleira." },
    { id: "figueira-de-castelo-rodrigo", name: "Figueira de Castelo Rodrigo", district: "Guarda", region: "centro",
      nickname: "Vila da Aldeia Histórica",
      description: "Vila-Mãe nas terras altas, amêndoa, vinho do Côa e abandono romântico." },
    { id: "fornos-de-algodres", name: "Fornos de Algodres", district: "Guarda",    region: "centro",
      nickname: "Vila do queijo da Serra",
      description: "Pequena, granítica, fria — adegas familiares e queijo amanteigado." },
    { id: "gouveia",           name: "Gouveia",             district: "Guarda",    region: "centro",
      nickname: "Princesa da Serra",
      description: "Porta da Estrela, museu Abel Manta, cerejas em Junho e neve em Janeiro." },
    { id: "manteigas",         name: "Manteigas",           district: "Guarda",    region: "centro",
      nickname: "Vila do Vale Glaciário do Zêzere",
      description: "Burel, Poço do Inferno, truta na grelha — a única vila dentro da Estrela." },
    { id: "meda",              name: "Mêda",                district: "Guarda",    region: "centro",
      nickname: "Vila do Côa",
      description: "Arte rupestre paleolítica nas pedras do Côa, oliveiras e maçã reineta." },
    { id: "pinhel",            name: "Pinhel",              district: "Guarda",    region: "centro",
      nickname: "Falcão da Beira",
      description: "Castelo medieval, casas brasonadas e o vinho generoso das terras altas." },
    { id: "sabugal",           name: "Sabugal",             district: "Guarda",    region: "centro",
      nickname: "Vila da Riba-Côa",
      description: "Côa a serpentear, Serra das Mesas e queijo, presunto e mel da raia." },
    { id: "seia",              name: "Seia",                district: "Guarda",    region: "centro",
      nickname: "Cidade do queijo e do pão",
      description: "Museu do Pão, Festa do Queijo Serra da Estrela, panorama sobre o Mondego." },
    { id: "trancoso",          name: "Trancoso",            district: "Guarda",    region: "centro",
      nickname: "Cidade-castelo de Bandarra",
      description: "Profecias do sapateiro, judiaria intacta e muralhas inteiras em redor." },
    { id: "vila-nova-de-foz-coa", name: "Vila Nova de Foz Côa", district: "Guarda", region: "norte",
      nickname: "Museu de arte paleolítica",
      description: "Gravuras ao ar livre com 25 mil anos, Património Mundial UNESCO." },

    // ─── DISTRITO DE LEIRIA ────────────────────────────────────────────────
    { id: "leiria",            name: "Leiria",              district: "Leiria",    region: "centro",
      nickname: "Cidade do Lis",
      description: "Castelo no monte, pinhal de D. Dinis e Rodrigo da Fonseca a vigiar a praça." },
    { id: "alcobaca",          name: "Alcobaça",            district: "Leiria",    region: "centro",
      nickname: "Cidade do amor de Pedro e Inês",
      description: "Mosteiro cisterciense UNESCO, túmulos lado a lado, doçaria conventual." },
    { id: "alvaiazere",        name: "Alvaiázere",          district: "Leiria",    region: "centro",
      nickname: "Capital do chícharo",
      description: "Leguminosa esquecida em pratos da serra, Aldeias do Xisto na vizinhança." },
    { id: "ansiao",            name: "Ansião",              district: "Leiria",    region: "centro",
      nickname: "Capital do cabrito assado",
      description: "Cabrito da Beira, vinho Bairrada e o Sicó a fazer fronteira ao Norte." },
    { id: "batalha",           name: "Batalha",             district: "Leiria",    region: "centro",
      nickname: "Cidade-Mosteiro UNESCO",
      description: "Promessa de D. João I após Aljubarrota — gótico-manuelino em pedra." },
    { id: "bombarral",         name: "Bombarral",           district: "Leiria",    region: "centro",
      nickname: "Capital da pera Rocha",
      description: "Buddha Eden, vinhos do Oeste e o pomar de pera mais doce do mundo." },
    { id: "caldas-da-rainha",  name: "Caldas da Rainha",    district: "Leiria",    region: "centro",
      nickname: "Cidade das águas",
      description: "Rainha D. Leonor fundou termas; cerâmica de Bordalo, frutas e mercado diário." },
    { id: "castanheira-de-pera", name: "Castanheira de Pêra", district: "Leiria",  region: "centro",
      nickname: "Vila das vendas",
      description: "Praia das Rocas — areia em montanha — chouriço de carne, queijo da serra." },
    { id: "figueiro-dos-vinhos", name: "Figueiró dos Vinhos", district: "Leiria",  region: "centro",
      nickname: "Aldeias do Xisto da Lousã",
      description: "Aldeia preservada, festival Bons Sons e o Zêzere a banhar a pé." },
    { id: "leiria-marinha-grande", name: "Marinha Grande", district: "Leiria",     region: "centro",
      nickname: "Cidade do vidro",
      description: "Fábricas de vidro centenárias, pinhal de Leiria e Praia da Vieira." },
    { id: "nazare",            name: "Nazaré",              district: "Leiria",    region: "centro",
      nickname: "Vila das ondas gigantes",
      description: "Sete saias da varina, 30 metros de mar e o farol do Sítio em pedestal." },
    { id: "obidos",            name: "Óbidos",              district: "Leiria",    region: "centro",
      nickname: "Vila-presente das rainhas",
      description: "Muralhas brancas, ginjinha em copo de chocolate, festival medieval e Natal." },
    { id: "pedrogao-grande",   name: "Pedrógão Grande",     district: "Leiria",    region: "centro",
      nickname: "Vila do Zêzere",
      description: "Praia fluvial, pinhal cortado pelo fogo de 2017 e a resiliência da Beira." },
    { id: "peniche",           name: "Peniche",             district: "Leiria",    region: "centro",
      nickname: "Capital da Onda",
      description: "Forte da prisão política, Berlengas no horizonte, surf de classe mundial." },
    { id: "pombal",            name: "Pombal",              district: "Leiria",    region: "centro",
      nickname: "Cidade do Marquês",
      description: "Sebastião José aqui exilado, castelo medieval e o Mondego a passar." },
    { id: "porto-de-mos",      name: "Porto de Mós",        district: "Leiria",    region: "centro",
      nickname: "Castelo verde do Sicó",
      description: "Castelo medieval com torres pintadas, pegadas de dinossauros e grutas." },

    // ─── DISTRITO DE LISBOA ────────────────────────────────────────────────
    { id: "lisboa",            name: "Lisboa",              district: "Lisboa",    region: "lisboa",
      nickname: "A cidade das sete colinas",
      description: "Tejo, eléctricos amarelos, fado e luz que pintou os olhos a Pessoa." },
    { id: "alenquer",          name: "Alenquer",            district: "Lisboa",    region: "centro",
      nickname: "Vila presépio",
      description: "Encosta com luzes em forma de Natal — Damião de Góis, vinhos do Oeste." },
    { id: "amadora",           name: "Amadora",             district: "Lisboa",    region: "lisboa",
      nickname: "Cidade dos cómicos",
      description: "Festival Amadora BD, terra de Herman José e a periferia que pulsa Lisboa." },
    { id: "arruda-dos-vinhos", name: "Arruda dos Vinhos",   district: "Lisboa",    region: "centro",
      nickname: "Linhas de Torres Vedras",
      description: "Frente de Wellington contra Massena, vinho do Oeste, calmaria do sul de Lisboa." },
    { id: "azambuja",          name: "Azambuja",            district: "Lisboa",    region: "centro",
      nickname: "A festa do largado",
      description: "Touros bravos pelas ruas, esteiros do Tejo e a lezíria a perder-se." },
    { id: "cadaval",           name: "Cadaval",             district: "Lisboa",    region: "centro",
      nickname: "Capital do pão de Vila Chã",
      description: "Maçã de Alcobaça, vinho do Oeste e o moinho a soprar das colinas." },
    { id: "cascais",           name: "Cascais",             district: "Lisboa",    region: "lisboa",
      nickname: "Vila dos Reis",
      description: "Estoril da realeza exilada, Boca do Inferno, Guincho ventoso, Pessoa cidadão." },
    { id: "lourinha",          name: "Lourinhã",            district: "Lisboa",    region: "centro",
      nickname: "Capital portuguesa do dinossauro",
      description: "Museu fóssil, agua-pé, maçã reineta e a Praia da Areia Branca." },
    { id: "loures",            name: "Loures",              district: "Lisboa",    region: "lisboa",
      nickname: "Vila do vinho de Bucelas",
      description: "Quintas, Arruda dos Vinhos à mão, e a azinhaga do D. Diogo Lopes Pacheco." },
    { id: "mafra",             name: "Mafra",               district: "Lisboa",    region: "lisboa",
      nickname: "Vila do Palácio-convento",
      description: "Monumento joanino, biblioteca rococó, Tapada de caça e Ericeira ao lado." },
    { id: "odivelas",          name: "Odivelas",            district: "Lisboa",    region: "lisboa",
      nickname: "Cidade do Mosteiro de S. Dinis",
      description: "Capital portuguesa do bolo de chocolate de Odivelas — receita oitocentista." },
    { id: "oeiras",            name: "Oeiras",              district: "Lisboa",    region: "lisboa",
      nickname: "A cidade dos sábios",
      description: "Marquês de Pombal teve aqui residência — investigação, ciência e a foz do Jamor." },
    { id: "sintra",            name: "Sintra",              district: "Lisboa",    region: "lisboa",
      nickname: "Paraíso na Terra (segundo Byron)",
      description: "Pena, Monserrate, Quinta da Regaleira, travesseiros e neblina dos Mouros." },
    { id: "sobral-de-monte-agraco", name: "Sobral de Monte Agraço", district: "Lisboa", region: "centro",
      nickname: "Linhas defensivas",
      description: "Forte do Alqueidão, Linhas de Torres e o vinho do Oeste a fluir." },
    { id: "torres-vedras",     name: "Torres Vedras",       district: "Lisboa",    region: "centro",
      nickname: "Capital do Carnaval mais português",
      description: "Carnaval sem brasileirice, vinho de Carcavelos e linhas de Wellington." },
    { id: "vila-franca-de-xira", name: "Vila Franca de Xira", district: "Lisboa", region: "lisboa",
      nickname: "Vila do colete encarnado",
      description: "Touradas, Festa do Avante, lezíria do Tejo e cavalos a galopar." },
    // Freguesias icónicas de Lisboa
    { id: "alfama",            name: "Alfama",              district: "Lisboa",    region: "lisboa",
      nickname: "O coração mouro de Lisboa",
      description: "Becos sobre o Tejo, fado nas tabernas e o Castelo de S. Jorge a mirar." },
    { id: "bairro-alto",       name: "Bairro Alto",         district: "Lisboa",    region: "lisboa",
      nickname: "A noite branca",
      description: "Boémia, fado pop, ateliers e o Pessoa que ali deambulou todas as madrugadas." },
    { id: "belem",             name: "Belém",               district: "Lisboa",    region: "lisboa",
      nickname: "A varanda dos Descobrimentos",
      description: "Mosteiro dos Jerónimos, Torre, pastéis e o Tejo a abrir-se para o Atlântico." },
    { id: "chiado",            name: "Chiado",              district: "Lisboa",    region: "lisboa",
      nickname: "Bairro literário",
      description: "Brasileira, Pessoa em bronze, livrarias antigas e cafés de mármore." },
    { id: "graca",             name: "Graça",               district: "Lisboa",    region: "lisboa",
      nickname: "Miradouro do Tejo",
      description: "Eléctrico 28, Senhora do Monte, pinheiros e o melhor pôr-do-sol da cidade." },
    { id: "mouraria",          name: "Mouraria",            district: "Lisboa",    region: "lisboa",
      nickname: "Berço do Fado",
      description: "Maria Severa, gente do mundo, cheiros de especiarias e a casa da Argentina." },
    { id: "parque-das-nacoes", name: "Parque das Nações",   district: "Lisboa",    region: "lisboa",
      nickname: "A Expo 98 que ficou",
      description: "Oceanário, Calatrava, telecabine, Tejo navegável — Lisboa do séc. XXI." },

    // ─── DISTRITO DE PORTALEGRE ────────────────────────────────────────────
    { id: "portalegre",        name: "Portalegre",          district: "Portalegre", region: "alentejo",
      nickname: "Cidade dos lanifícios",
      description: "Tapeçaria de Portalegre, Serra de São Mamede e José Régio à porta." },
    { id: "alter-do-chao",     name: "Alter do Chão",       district: "Portalegre", region: "alentejo",
      nickname: "Berço do cavalo Alter Real",
      description: "Coudelaria real, ponte romana e Vila Romana de Tongóbriga ao lado." },
    { id: "arronches",         name: "Arronches",           district: "Portalegre", region: "alentejo",
      nickname: "Vila raiana",
      description: "Castelo de S. Pedro, queijo de cabra e a Serra de São Mamede em redor." },
    { id: "avis",              name: "Avis",                district: "Portalegre", region: "alentejo",
      nickname: "Berço da Dinastia de Avis",
      description: "Aqui D. João I foi Mestre — castelo de Avis sobre a barragem do Maranhão." },
    { id: "campo-maior",       name: "Campo Maior",         district: "Portalegre", region: "alentejo",
      nickname: "Vila das flores de papel",
      description: "Festa do Povo cobre as ruas a cada quatro anos — Delta Cafés vem daqui." },
    { id: "castelo-de-vide",   name: "Castelo de Vide",     district: "Portalegre", region: "alentejo",
      nickname: "Sintra do Alentejo",
      description: "Judiaria medieval, fonte da vila, frescura da Serra de São Mamede." },
    { id: "crato",             name: "Crato",               district: "Portalegre", region: "alentejo",
      nickname: "Convento de Flor da Rosa",
      description: "Pousada de Portugal templária, peças de oleiro e mosteiro hospitalário." },
    { id: "elvas",             name: "Elvas",               district: "Portalegre", region: "alentejo",
      nickname: "Cidade-fortaleza UNESCO",
      description: "Maior conjunto abaluartado do mundo, ameixa rainha-claudia e queijo." },
    { id: "fronteira",         name: "Fronteira",           district: "Portalegre", region: "alentejo",
      nickname: "Vila branca da raia",
      description: "Cante alentejano, sobreiro centenário e o silêncio do azinhal." },
    { id: "gaviao",             name: "Gavião",             district: "Portalegre", region: "alentejo",
      nickname: "Vila pesqueira do Tejo",
      description: "Albufeira de Belver, sável, lampreia e o castelo no penhasco." },
    { id: "marvao",            name: "Marvão",              district: "Portalegre", region: "alentejo",
      nickname: "O ninho da águia",
      description: "Aldeia medieval no topo da serra — vista para metade do reino e Espanha." },
    { id: "monforte",          name: "Monforte",            district: "Portalegre", region: "alentejo",
      nickname: "Vila do azeite",
      description: "Mosaico romano de Torre de Palma, olival e azinheiras infinitas." },
    { id: "nisa",              name: "Nisa",                district: "Portalegre", region: "alentejo",
      nickname: "Capital do queijo de Nisa",
      description: "Queijo de ovelha em saco de papel, olaria branca pintada com sangue de boi." },
    { id: "ponte-de-sor",      name: "Ponte de Sor",        district: "Portalegre", region: "alentejo",
      nickname: "Capital da cortiça",
      description: "Sobreiros, balão de ar quente em festival, fábricas que cortam cortiça ao mundo." },
    { id: "sousel",            name: "Sousel",              district: "Portalegre", region: "alentejo",
      nickname: "Terra do tinto encorpado",
      description: "Cante, açorda alentejana, mármore e a planície a derreter no Verão." },

    // ─── DISTRITO DO PORTO ─────────────────────────────────────────────────
    { id: "porto",             name: "Porto",               district: "Porto",     region: "norte",
      nickname: "Cidade Invicta",
      description: "Granito, vinho do Porto, Ribeira UNESCO, francesinha e a alma que nunca rendeu." },
    { id: "amarante",          name: "Amarante",            district: "Porto",     region: "norte",
      nickname: "Cidade de S. Gonçalo",
      description: "Doces fálicos do santo casamenteiro, ponte sobre o Tâmega, Vinho Verde." },
    { id: "baiao",             name: "Baião",               district: "Porto",     region: "norte",
      nickname: "Vila do Marão",
      description: "Aguardente bagaceira, broa de avintes e os caminhos a subir a Serra." },
    { id: "felgueiras",        name: "Felgueiras",          district: "Porto",     region: "norte",
      nickname: "Cidade do calçado e do solar",
      description: "Solares brasonados, casa-museu de Sampaio Bruno e indústria têxtil." },
    { id: "gondomar",          name: "Gondomar",            district: "Porto",     region: "norte",
      nickname: "Capital da filigrana",
      description: "Coração português em fio de ouro, ourivesaria patrimonial e o Douro a passar." },
    { id: "lousada",           name: "Lousada",             district: "Porto",     region: "norte",
      nickname: "Capital do românico",
      description: "Rota do românico, mosteiros do séc. XII e queijo curado da Cara." },
    { id: "maia",              name: "Maia",                district: "Porto",     region: "norte",
      nickname: "Cidade-aeroporto",
      description: "Indústria, Castêlo da Maia (basquete) e o aeroporto Francisco Sá Carneiro." },
    { id: "marco-de-canaveses", name: "Marco de Canaveses", district: "Porto",     region: "norte",
      nickname: "Cidade do românico do Tâmega",
      description: "Igreja de Siza Vieira, Tongóbriga romana, vinhos Verdes do Sousa." },
    { id: "matosinhos",        name: "Matosinhos",          district: "Porto",     region: "norte",
      nickname: "Capital da sardinha",
      description: "Mercado peixeiro, Piscinas das Marés de Siza e Leixões a movimentar contentores." },
    { id: "paco-de-sousa",     name: "Paços de Ferreira",   district: "Porto",     region: "norte",
      nickname: "Capital do móvel",
      description: "Fábricas de mobiliário, Citadinos no estádio e o mosteiro de Ferreira." },
    { id: "paredes",           name: "Paredes",             district: "Porto",     region: "norte",
      nickname: "Capital do design e mobiliário",
      description: "Cidade jovem em formato pólo industrial — design contemporâneo no Sousa." },
    { id: "penafiel",          name: "Penafiel",            district: "Porto",     region: "norte",
      nickname: "Cidade do Sameiro",
      description: "Castelo dos castelos, granito jovem, Vinho Verde Penafiel e termas de S. Vicente." },
    { id: "povoa-de-varzim",   name: "Póvoa de Varzim",     district: "Porto",     region: "norte",
      nickname: "Cidade dos pescadores e do casino",
      description: "Praia, casino, Eça residiu aqui — terra dos junqueiros e siglas poveiras." },
    { id: "santo-tirso",       name: "Santo Tirso",         district: "Porto",     region: "norte",
      nickname: "Cidade do mosteiro beneditino",
      description: "Parque de escultura ao ar livre, Vinho Verde e o ave a costurar paisagens." },
    { id: "trofa",             name: "Trofa",               district: "Porto",     region: "norte",
      nickname: "Cidade da Estação",
      description: "Cidade jovem do Vale do Ave — encruzilhada ferroviária histórica." },
    { id: "valongo",           name: "Valongo",             district: "Porto",     region: "norte",
      nickname: "Capital da ardósia e da regueifa",
      description: "Pão lousado em corda, biscoitos e a Serra de Santa Justa para passear." },
    { id: "vila-do-conde",     name: "Vila do Conde",       district: "Porto",     region: "norte",
      nickname: "Cidade dos descobrimentos do Norte",
      description: "Naus, rendas de bilros, aqueduto e o Ave a desaguar." },
    { id: "vila-nova-de-gaia", name: "Vila Nova de Gaia",   district: "Porto",     region: "norte",
      nickname: "Cidade do Vinho do Porto",
      description: "Caves de Vinho do Porto, rabelos no Douro, Serra do Pilar a olhar a Invicta." },
    { id: "ribeira",           name: "Ribeira",             district: "Porto",     region: "norte",
      nickname: "O cais Património Mundial",
      description: "Casario empilhado a cair sobre o Douro, jantares à beira-rio e fado portuense." },
    { id: "foz-do-douro",      name: "Foz do Douro",        district: "Porto",     region: "norte",
      nickname: "Onde o Douro encontra o mar",
      description: "Burgo balnear, Pérgola da Foz e os pôres-do-sol mais famosos da cidade." },

    // ─── DISTRITO DE SANTARÉM ──────────────────────────────────────────────
    { id: "santarem",          name: "Santarém",            district: "Santarém",  region: "centro",
      nickname: "Capital do Ribatejo",
      description: "Gótico florido, miradouro sobre a lezíria do Tejo e a Festa do Campino." },
    { id: "abrantes",          name: "Abrantes",            district: "Santarém",  region: "centro",
      nickname: "Vila do Tejo a meio do reino",
      description: "Palha de Abrantes (doce de gema), castelo e o Tejo a navegar." },
    { id: "almeirim",          name: "Almeirim",            district: "Santarém",  region: "centro",
      nickname: "Capital da sopa da pedra",
      description: "Lenda do frade da sopa, lezíria, melão de Almeirim e tasca à mesa." },
    { id: "alpiarca",          name: "Alpiarça",            district: "Santarém",  region: "centro",
      nickname: "Vila do José Relvas",
      description: "Casa-Museu dos Patudos, cavalo lusitano e Sociedade Patudense." },
    { id: "benavente",         name: "Benavente",           district: "Santarém",  region: "centro",
      nickname: "Vila do toiro bravo",
      description: "Coudelaria histórica, lezíria do Tejo e a Festa do Toiro em Setembro." },
    { id: "cartaxo",           name: "Cartaxo",             district: "Santarém",  region: "centro",
      nickname: "Capital do vinho",
      description: "Festa do Vinho de Maio, museu rural e do vinho — Ribatejo a fermentar." },
    { id: "chamusca",          name: "Chamusca",            district: "Santarém",  region: "centro",
      nickname: "Capital do cavalo",
      description: "Lezíria, cavaleiros da Casa do Cavalo, festa anual com touradas." },
    { id: "constancia",        name: "Constância",          district: "Santarém",  region: "centro",
      nickname: "Vila-poema de Camões",
      description: "Aqui exilado, escreveu episódios d'Os Lusíadas — pomba branca a flutuar." },
    { id: "coruche",           name: "Coruche",             district: "Santarém",  region: "centro",
      nickname: "Capital mundial do sobreiro",
      description: "Sobreiro Monumental do Assento, cortiça e arroz da lezíria do Sorraia." },
    { id: "entroncamento",     name: "Entroncamento",       district: "Santarém",  region: "centro",
      nickname: "Cidade dos comboios",
      description: "Encruzilhada ferroviária, Museu Nacional Ferroviário e cidade mais nova." },
    { id: "ferreira-do-zezere", name: "Ferreira do Zêzere", district: "Santarém",  region: "centro",
      nickname: "Vila do Castelo do Bode",
      description: "Albufeira azul, praias fluviais e o sabor das migas em barro." },
    { id: "golega",            name: "Golegã",              district: "Santarém",  region: "centro",
      nickname: "Capital do cavalo lusitano",
      description: "Feira do Cavalo de Novembro, água-pé, castanha-assada e capote." },
    { id: "ourem",             name: "Ourém",               district: "Santarém",  region: "centro",
      nickname: "Vila do Conde de Ourém",
      description: "Castelo gótico, Santuário de Fátima a uns passos e doce conventual." },
    { id: "rio-maior",         name: "Rio Maior",           district: "Santarém",  region: "centro",
      nickname: "Vila das salinas de água doce",
      description: "Salinas de Rio Maior — únicas no interior — fátima a 15 minutos." },
    { id: "salvaterra-de-magos", name: "Salvaterra de Magos", district: "Santarém", region: "centro",
      nickname: "Vila da falcoaria real",
      description: "Falcoaria de D. José, lezíria do Tejo e arroz Carolino do Sorraia." },
    { id: "tomar",             name: "Tomar",               district: "Santarém",  region: "centro",
      nickname: "Cidade dos Templários",
      description: "Convento de Cristo UNESCO, Festa dos Tabuleiros e Mata dos Sete Montes." },
    { id: "torres-novas",      name: "Torres Novas",        district: "Santarém",  region: "centro",
      nickname: "Cidade entre rios",
      description: "Castelo bem conservado, mosaicos romanos do Cabeço de Vide e queijo Carraz." },

    // ─── DISTRITO DE SETÚBAL ───────────────────────────────────────────────
    { id: "setubal",           name: "Setúbal",             district: "Setúbal",   region: "lisboa",
      nickname: "Cidade do choco frito",
      description: "Sado, golfinhos, Arrábida em pano de fundo e Bocage a recitar décimas." },
    { id: "alcacer-do-sal",    name: "Alcácer do Sal",      district: "Setúbal",   region: "alentejo",
      nickname: "Vila branca do Sado",
      description: "Cegonhas a nidificar nos campanários, arroz Carolino do Sado, pousada-castelo." },
    { id: "alcochete",         name: "Alcochete",           district: "Setúbal",   region: "lisboa",
      nickname: "Vila salineira do Tejo",
      description: "Sal de flor, salinas, terra adoptiva de Vasco da Gama e Estuário do Tejo." },
    { id: "almada",            name: "Almada",              district: "Setúbal",   region: "lisboa",
      nickname: "Cidade do Cristo Rei",
      description: "Vista para Lisboa do outro lado do Tejo, costa da Caparica em frente ao Atlântico." },
    { id: "barreiro",          name: "Barreiro",            district: "Setúbal",   region: "lisboa",
      nickname: "Cidade operária do Tejo",
      description: "CUF, sociedades recreativas, rock'n'roll e o barco a sair às 7h para Lisboa." },
    { id: "grandola",          name: "Grândola",            district: "Setúbal",   region: "alentejo",
      nickname: "Vila Morena",
      description: "Zeca Afonso e o 25 de Abril, montado, fadigas e o Cante a cantar a liberdade." },
    { id: "moita",             name: "Moita",               district: "Setúbal",   region: "lisboa",
      nickname: "Vila ribeirinha do Tejo",
      description: "Avieiros, varinos, vinho moscatel e o sotaque doce da margem-sul." },
    { id: "montijo",           name: "Montijo",             district: "Setúbal",   region: "lisboa",
      nickname: "Vila das touradas",
      description: "Maior cidade da margem sul, corridas de touros e cavalos a galopar." },
    { id: "palmela",           name: "Palmela",             district: "Setúbal",   region: "lisboa",
      nickname: "Castelo do moscatel",
      description: "Pousada no castelo templário, vinho moscatel de Setúbal e laranja da terra." },
    { id: "santiago-do-cacem", name: "Santiago do Cacém",   district: "Setúbal",   region: "alentejo",
      nickname: "Vila branca da costa",
      description: "Mirobriga romana, Lagoa de Santo André, Costa Vicentina ao lado." },
    { id: "seixal",            name: "Seixal",              district: "Setúbal",   region: "lisboa",
      nickname: "Vila operária do Tejo",
      description: "Moinho de maré, ecomuseu industrial e a Mata Nacional dos Medos." },
    { id: "sesimbra",          name: "Sesimbra",            district: "Setúbal",   region: "lisboa",
      nickname: "Vila pesqueira do espadarte",
      description: "Bom Jesus no Cabo Espichel, Arrábida verde-azul e o peixe assado na pedra." },
    { id: "sines",             name: "Sines",               district: "Setúbal",   region: "alentejo",
      nickname: "Cidade de Vasco da Gama",
      description: "Festas Sines World Music, porto industrial e a praia atlântica selvagem." },

    // ─── DISTRITO DE VIANA DO CASTELO ──────────────────────────────────────
    { id: "viana-do-castelo",  name: "Viana do Castelo",    district: "Viana do Castelo", region: "norte",
      nickname: "Princesa do Lima",
      description: "Senhora da Agonia, ouro filigrana, lenços bordados e o coração mais bordado do mundo." },
    { id: "arcos-de-valdevez", name: "Arcos de Valdevez",   district: "Viana do Castelo", region: "norte",
      nickname: "Berço de Portugal",
      description: "Aqui em 1141 D. Afonso Henriques ganhou independência — Lindoso, Soajo, Peneda." },
    { id: "caminha",           name: "Caminha",             district: "Viana do Castelo", region: "norte",
      nickname: "Vila do Coura",
      description: "Foz do Minho, ferry para Espanha, Insua e a Serra d'Arga em pano de fundo." },
    { id: "melgaco",           name: "Melgaço",             district: "Viana do Castelo", region: "norte",
      nickname: "Capital do Alvarinho",
      description: "Vinho verde Alvarinho premiado, Castro Laboreiro e o Peneda-Gerês." },
    { id: "moncao",            name: "Monção",              district: "Viana do Castelo", region: "norte",
      nickname: "Vila do Alvarinho e do Lampreia",
      description: "Alvarinho, lampreia à bordalesa e Deu-la-Deu Martins a expulsar castelhanos." },
    { id: "paredes-de-coura",  name: "Paredes de Coura",    district: "Viana do Castelo", region: "norte",
      nickname: "Vila do Festival",
      description: "Festival de Vilar de Mouros em outra época, hoje o Paredes de Coura indie." },
    { id: "ponte-da-barca",    name: "Ponte da Barca",      district: "Viana do Castelo", region: "norte",
      nickname: "Vila portal do Gerês",
      description: "Lima a fluir, ponte renascentista e os altos da Serra Amarela." },
    { id: "ponte-de-lima",     name: "Ponte de Lima",       district: "Viana do Castelo", region: "norte",
      nickname: "A vila mais antiga de Portugal",
      description: "Feiras Novas, ponte romana, Vinho Verde Loureiro e o rio mais belo do reino." },
    { id: "valenca",           name: "Valença",             district: "Viana do Castelo", region: "norte",
      nickname: "Vila-fortaleza do Minho",
      description: "Praça-forte abaluartada, comércio luso-galego e o Caminho de Santiago." },
    { id: "vila-nova-de-cerveira", name: "Vila Nova de Cerveira", district: "Viana do Castelo", region: "norte",
      nickname: "Vila das artes",
      description: "Bienal Internacional de Arte, ferry para Espanha e Lobo Ibérico no monte." },

    // ─── DISTRITO DE VILA REAL ─────────────────────────────────────────────
    { id: "vila-real",         name: "Vila Real",           district: "Vila Real", region: "norte",
      nickname: "Princesa do Corgo",
      description: "Solar de Mateus, Universidade UTAD e o Marão a separar do litoral." },
    { id: "alijo",             name: "Alijó",               district: "Vila Real", region: "norte",
      nickname: "Capital do Douro Superior",
      description: "Pinhão a uns passos, vinha em socalcos UNESCO, Vinho do Porto envelhecido." },
    { id: "boticas",           name: "Boticas",             district: "Vila Real", region: "norte",
      nickname: "Terra do vinho dos mortos",
      description: "Vinho enterrado em garrafas — descobertas anos depois — fumeiro e Barroso." },
    { id: "chaves",            name: "Chaves",              district: "Vila Real", region: "norte",
      nickname: "Aquae Flaviae",
      description: "Termas romanas, ponte de Trajano, presunto premiado e pastéis de Chaves." },
    { id: "mesao-frio",        name: "Mesão Frio",          district: "Vila Real", region: "norte",
      nickname: "Porta do Douro",
      description: "Solar de Rede, Douro a entrar pelo Vinhateiro e quintas vitivinícolas." },
    { id: "mondim-de-basto",   name: "Mondim de Basto",     district: "Vila Real", region: "norte",
      nickname: "Berço da Senhora da Graça",
      description: "Estátua do Cavaleiro de Basto, montes do Alvão e cabra serrana." },
    { id: "montalegre",        name: "Montalegre",          district: "Vila Real", region: "norte",
      nickname: "Capital do Barroso",
      description: "Sexta-feira 13 com bruxas, Barrosã premiada e o frio de Trás-os-Montes." },
    { id: "murca",             name: "Murça",               district: "Vila Real", region: "norte",
      nickname: "Vila do Porco da Murça",
      description: "Berrão pré-romano em pedra, vinho Douro Superior e azeite premiado." },
    { id: "peso-da-regua",     name: "Peso da Régua",       district: "Vila Real", region: "norte",
      nickname: "Capital do Vinho do Porto",
      description: "Museu do Douro, comboio histórico, quintas em socalcos UNESCO." },
    { id: "ribeira-de-pena",   name: "Ribeira de Pena",     district: "Vila Real", region: "norte",
      nickname: "Vila do Camilo Castelo Branco",
      description: "Casa do escritor, Praia Fluvial do Cavalum e o Tâmega a cantar." },
    { id: "sabrosa",           name: "Sabrosa",             district: "Vila Real", region: "norte",
      nickname: "Berço de Fernão de Magalhães",
      description: "Casa do navegador, vinhas do Douro, vinho do Porto Vintage." },
    { id: "santa-marta-de-penaguiao", name: "Santa Marta de Penaguião", district: "Vila Real", region: "norte",
      nickname: "Vila do vinho do Porto",
      description: "Adegas centenárias, comboio do Douro e a Festa da Vindima." },
    { id: "valpacos",          name: "Valpaços",            district: "Vila Real", region: "norte",
      nickname: "Capital do azeite e da castanha",
      description: "Olival, soutos, presunto, fumeiro — Trás-os-Montes em estado puro." },

    // ─── DISTRITO DE VISEU ─────────────────────────────────────────────────
    { id: "viseu",             name: "Viseu",               district: "Viseu",     region: "centro",
      nickname: "Cidade-jardim do Dão",
      description: "Sé granítica, Grão Vasco, Cava do Viriato e o Dão a fermentar." },
    { id: "armamar",           name: "Armamar",             district: "Viseu",     region: "norte",
      nickname: "Vila da maçã do Douro",
      description: "Maçã de montanha, Douro Vinhateiro e a barragem de Bagaúste." },
    { id: "carregal-do-sal",   name: "Carregal do Sal",     district: "Viseu",     region: "centro",
      nickname: "Vila da Casa de Bragança",
      description: "Castelo de Cabriz, Dão de várias castas e fumeiro da Beira." },
    { id: "castro-daire",      name: "Castro Daire",        district: "Viseu",     region: "centro",
      nickname: "Vila da Montemuro",
      description: "Serra de Montemuro, casas de granito e o Paiva a esculpir vales." },
    { id: "cinfaes",           name: "Cinfães",             district: "Viseu",     region: "norte",
      nickname: "Vila do Douro Verde",
      description: "Margem sul do Douro, mosteiro de Tarouquela e o Paiva selvagem." },
    { id: "lamego",            name: "Lamego",              district: "Viseu",     region: "norte",
      nickname: "Cidade dos espumantes e do presunto",
      description: "Nossa Senhora dos Remédios e escadaria barroca, raposeira nas adegas." },
    { id: "mangualde",         name: "Mangualde",           district: "Viseu",     region: "centro",
      nickname: "Vila do Dão",
      description: "Indústria automóvel, Citroën e Peugeot, palácio dos Anadia." },
    { id: "moimenta-da-beira", name: "Moimenta da Beira",   district: "Viseu",     region: "norte",
      nickname: "Capital da maçã",
      description: "Maçã de montanha, cereja, vinhos do Távora-Varosa espumantes." },
    { id: "mortagua",          name: "Mortágua",            district: "Viseu",     region: "centro",
      nickname: "Vila do Mondego",
      description: "Caldas da Felgueira, eucaliptal e a barragem da Aguieira." },
    { id: "nelas",             name: "Nelas",               district: "Viseu",     region: "centro",
      nickname: "Vila do Dão",
      description: "Quinta da Cabriz, Encontro do Dão, festa do vinho e queijo serrano." },
    { id: "oliveira-de-frades", name: "Oliveira de Frades", district: "Viseu",    region: "centro",
      nickname: "Vila do Caramulo",
      description: "Serra do Caramulo, Museu do Automóvel e ar de altitude." },
    { id: "penalva-do-castelo", name: "Penalva do Castelo", district: "Viseu",    region: "centro",
      nickname: "Vila do Casal de Loivos",
      description: "Casa da Ínsua, Dão, açúcar mascavado e maçã de Penalva." },
    { id: "penedono",          name: "Penedono",            district: "Viseu",     region: "norte",
      nickname: "Vila do Magriço",
      description: "Castelo dos Doze de Inglaterra, planalto granítico e ginja." },
    { id: "resende",           name: "Resende",             district: "Viseu",     region: "norte",
      nickname: "Vila da cereja",
      description: "Cerejeiras em flor sobre o Douro, Pego da Murta e Paiva selvagem." },
    { id: "santa-comba-dao",   name: "Santa Comba Dão",     district: "Viseu",     region: "centro",
      nickname: "Vila do Dão",
      description: "Terra natal de Salazar, museus do Caramulo a uns minutos, Dão tinto." },
    { id: "sao-pedro-do-sul",  name: "São Pedro do Sul",    district: "Viseu",     region: "centro",
      nickname: "Capital das termas",
      description: "Águas que terão curado D. Afonso Henriques após a Batalha de Badajoz." },
    { id: "tabuaco",           name: "Tabuaço",             district: "Viseu",     region: "norte",
      nickname: "Vila do Távora",
      description: "Espumantes Távora-Varosa, vinha em socalco e amêndoa em flor." },
    { id: "tarouca",           name: "Tarouca",             district: "Viseu",     region: "norte",
      nickname: "Vila cisterciense",
      description: "Mosteiro de S. João de Tarouca, maçã e o vinho do Douro Sul." },
    { id: "tondela",           name: "Tondela",             district: "Viseu",     region: "centro",
      nickname: "Vila do Caramulo",
      description: "Estádio dos Tondelenses, museu Abel Lacerda, queijo do Caramulo." },
    { id: "vouzela",           name: "Vouzela",             district: "Viseu",     region: "centro",
      nickname: "Vila dos pastéis",
      description: "Pastéis de Vouzela, Lafões histórico, vinho do Lafões verde-rubi." },

    // ─── REGIÃO AUTÓNOMA DA MADEIRA ────────────────────────────────────────
    { id: "funchal",           name: "Funchal",             district: "Madeira",   region: "madeira",
      nickname: "Cidade-jardim do Atlântico",
      description: "Carros de cesto do Monte, mercado dos Lavradores, vinho da Madeira e Réveillon." },
    { id: "calheta-madeira",   name: "Calheta",             district: "Madeira",   region: "madeira",
      nickname: "Vila do mel-de-cana",
      description: "Único engenho açucareiro a funcionar, areia dourada e a Casa das Mudas." },
    { id: "camara-de-lobos",   name: "Câmara de Lobos",     district: "Madeira",   region: "madeira",
      nickname: "Vila de Churchill",
      description: "Churchill pintou aqui, poncha forte, espadarte e vinhas em socalcos." },
    { id: "machico",           name: "Machico",             district: "Madeira",   region: "madeira",
      nickname: "Berço da Madeira",
      description: "Onde Zarco e Tristão chegaram em 1419 — capela do Cristo Milagroso." },
    { id: "ponta-do-sol",      name: "Ponta do Sol",        district: "Madeira",   region: "madeira",
      nickname: "Vila do sol da Madeira",
      description: "Mais horas de sol da ilha, ribeiras encaixadas e plantação de banana." },
    { id: "porto-moniz",       name: "Porto Moniz",         district: "Madeira",   region: "madeira",
      nickname: "Vila das piscinas naturais",
      description: "Piscinas vulcânicas, levadas e a ponta noroeste mais selvagem da ilha." },
    { id: "porto-santo",       name: "Porto Santo",         district: "Madeira",   region: "madeira",
      nickname: "Ilha dourada",
      description: "Praia de 9 km de areia terapêutica, casa de Colombo e vinho leve." },
    { id: "ribeira-brava",     name: "Ribeira Brava",       district: "Madeira",   region: "madeira",
      nickname: "Vila da Ribeira",
      description: "Capela manuelina à beira-mar, mercado do peixe e bordados madeirenses." },
    { id: "santa-cruz-madeira", name: "Santa Cruz",         district: "Madeira",   region: "madeira",
      nickname: "Vila aeroportuária",
      description: "Pista por cima do mar, praias e o Aquaparque dos miúdos." },
    { id: "santana",           name: "Santana",             district: "Madeira",   region: "madeira",
      nickname: "Vila das casas de colmo",
      description: "Casas triangulares pintadas, Reserva da Biosfera e o Pico Ruivo a subir." },
    { id: "sao-vicente-madeira", name: "São Vicente",       district: "Madeira",   region: "madeira",
      nickname: "Vila das grutas vulcânicas",
      description: "Centro do Vulcanismo, igreja branca à beira-mar e levadas no monte." },

    // ─── REGIÃO AUTÓNOMA DOS AÇORES ────────────────────────────────────────
    { id: "ponta-delgada",     name: "Ponta Delgada",       district: "Açores",    region: "acores",
      nickname: "Capital dos Açores",
      description: "Portas da Cidade, ananás dos Açores e a ilha de São Miguel a chamar." },
    { id: "angra-do-heroismo", name: "Angra do Heroísmo",   district: "Açores",    region: "acores",
      nickname: "Cidade UNESCO da Terceira",
      description: "Primeira escala atlântica, baluartes, touradas à corda e Sanjoaninas." },
    { id: "horta",             name: "Horta",               district: "Açores",    region: "acores",
      nickname: "Vila do Peter Café Sport",
      description: "Marina pintada pelos veleiros do Atlântico, gin tónico e Faial-Pico em frente." },
    { id: "ribeira-grande-acores", name: "Ribeira Grande",  district: "Açores",    region: "acores",
      nickname: "Vila histórica de S. Miguel",
      description: "Caldeiras de Furnas, plantação de chá da Gorreana e Lagoa do Fogo." },
    { id: "lagoa-acores",      name: "Lagoa",               district: "Açores",    region: "acores",
      nickname: "Cidade do Carlos Bicudo",
      description: "Atalhada, vinhas de Caloura e zonas balneares acolhedoras de S. Miguel." },
    { id: "vila-do-porto",     name: "Vila do Porto",       district: "Açores",    region: "acores",
      nickname: "Capital de Santa Maria",
      description: "Ilha amarela, Praia Formosa, primeira ilha a ser descoberta dos Açores." },
    { id: "praia-da-vitoria",  name: "Praia da Vitória",    district: "Açores",    region: "acores",
      nickname: "Cidade da Praia",
      description: "Base das Lajes, Festas da Praia em Agosto e baía protegida da Terceira." },
    { id: "santa-cruz-graciosa", name: "Santa Cruz da Graciosa", district: "Açores", region: "acores",
      nickname: "Vila branca da Graciosa",
      description: "Ilha-museu UNESCO, moinhos holandeses e a Furna do Enxofre." },
    { id: "velas",             name: "Velas",               district: "Açores",    region: "acores",
      nickname: "Vila de São Jorge",
      description: "Queijo de São Jorge premiado, fajãs costeiras e a Lagoa do Sant'Cristo." },
    { id: "calheta-acores",    name: "Calheta",             district: "Açores",    region: "acores",
      nickname: "Capital da fajã",
      description: "Fajã dos Cubres, festival Wave Caparica e o São Jorge mais verde." },
    { id: "madalena",          name: "Madalena",            district: "Açores",    region: "acores",
      nickname: "Vila do Pico",
      description: "Vinha em chãos de basalto UNESCO, montanha mais alta de Portugal a 2351m." },
    { id: "lajes-do-pico",     name: "Lajes do Pico",       district: "Açores",    region: "acores",
      nickname: "Vila baleeira",
      description: "Museu dos Baleeiros, observação de cetáceos e o Pico em silhueta." },
    { id: "vila-da-povoacao",  name: "Povoação",            district: "Açores",    region: "acores",
      nickname: "Primeira povoação dos Açores",
      description: "Onde tudo começou em 1432, Furnas a uns minutos, fervores e ananás." },
    { id: "santa-cruz-flores", name: "Santa Cruz das Flores", district: "Açores",  region: "acores",
      nickname: "Vila ocidental",
      description: "Ilha das hortênsias, Lagoa Funda, ponto mais ocidental da Europa." },
    { id: "lajes-das-flores",  name: "Lajes das Flores",    district: "Açores",    region: "acores",
      nickname: "Vila florida",
      description: "Hortênsias, cascatas verticais e baías para foragir do mundo." },
    { id: "vila-do-corvo",     name: "Vila do Corvo",       district: "Açores",    region: "acores",
      nickname: "A única vila do Corvo",
      description: "430 habitantes numa cratera vulcânica, a ilha mais pequena dos Açores." },
    { id: "nordeste-acores",   name: "Nordeste",            district: "Açores",    region: "acores",
      nickname: "Vila das hortênsias e do chá",
      description: "Plantação de chá, miradouros sobre o Atlântico e estradas em flor." },

    // ─── DIÁSPORA & FREGUESIAS ICÓNICAS EXTRA ──────────────────────────────
    { id: "ericeira",          name: "Ericeira",            district: "Lisboa",    region: "lisboa",
      nickname: "Reserva Mundial de Surf",
      description: "Sete spots, ouriço-do-mar, pescadores e cervejas ao pôr-do-sol." },
    { id: "carcavelos",        name: "Carcavelos",          district: "Lisboa",    region: "lisboa",
      nickname: "Praia da Linha",
      description: "Surf urbano, Forte de São Julião e a beach-volley do verão lisboeta." },
    { id: "estoril",           name: "Estoril",             district: "Lisboa",    region: "lisboa",
      nickname: "Riviera Portuguesa",
      description: "Casino que inspirou Casino Royale, autódromo e palmeiras a brilhar." },
    { id: "costa-da-caparica", name: "Costa da Caparica",   district: "Setúbal",   region: "lisboa",
      nickname: "Praia de Lisboa",
      description: "Comboio amarelo nas dunas, 24 km de areia e o Verão da capital." },
    { id: "fatima",            name: "Fátima",              district: "Santarém",  region: "centro",
      nickname: "Santuário Mariano",
      description: "Aparições de 1917, peregrinações a 13 de Maio e Outubro." },
    { id: "luso",              name: "Luso",                district: "Aveiro",    region: "centro",
      nickname: "Vila termal do Buçaco",
      description: "Mata do Buçaco, Palace Hotel romântico e água Luso da fonte." },
    { id: "vilamoura",         name: "Vilamoura",           district: "Faro",      region: "algarve",
      nickname: "A marina dos iates",
      description: "Resort planeado dos anos 70, golfe, ruínas romanas e nightlife." },
    { id: "geres",             name: "Gerês",               district: "Braga",     region: "norte",
      nickname: "Parque Nacional",
      description: "Único Parque Nacional do país — lobos, cascatas e geira romana." },
    { id: "monsanto",          name: "Monsanto",            district: "Castelo Branco", region: "centro",
      nickname: "A aldeia mais portuguesa",
      description: "Casas entre rochedos, castelo no topo e galo de prata em 1938." },
    { id: "piodao",            name: "Piódão",              district: "Coimbra",   region: "centro",
      nickname: "Aldeia presépio",
      description: "Casas em xisto azul, igreja branca e Serra do Açor em redor." },
    { id: "monsaraz",          name: "Monsaraz",            district: "Évora",     region: "alentejo",
      nickname: "Vila medieval no Alqueva",
      description: "Vila amuralhada sobre o maior lago artificial da Europa." },
    { id: "marvao-aldeia",     name: "Pavia",               district: "Évora",     region: "alentejo",
      nickname: "Vila da Anta",
      description: "Anta-capela de S. Dinis dentro do dólmen — sincretismo único." },
    { id: "luanda",            name: "Luanda",              district: "Diáspora",  region: "lisboa",
      nickname: "Diáspora — capital de Angola",
      description: "Para os portugueses que vivem ou viveram em Angola — comunidade luso-angolana." },
    { id: "paris",             name: "Paris",               district: "Diáspora",  region: "lisboa",
      nickname: "Diáspora — Île-de-France",
      description: "Onde mora a maior comunidade portuguesa do estrangeiro." },
    { id: "geneve",            name: "Genebra",             district: "Diáspora",  region: "lisboa",
      nickname: "Diáspora — Suíça romanda",
      description: "Onde se entrelaçam famílias portuguesas há três gerações." },
    { id: "londres",           name: "Londres",             district: "Diáspora",  region: "lisboa",
      nickname: "Diáspora — Reino Unido",
      description: "Brexit afastou alguns, ficaram as pastelarias, o fado e as comunidades." },
    { id: "macau",             name: "Macau",               district: "Diáspora",  region: "lisboa",
      nickname: "Diáspora — Sul da China",
      description: "Pastel de nata, calçada à portuguesa e Macau de quatro séculos." },
];

// ───────────────────────── HELPERS ──────────────────────────────────────────

const _stripAccents = (s) =>
    (s || "").toString().toLowerCase()
        .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
        .replace(/[ñ]/g, "n");

/**
 * Pesquisa fuzzy insensível a acentos.
 * Devolve até `limit` cidades ordenadas por relevância:
 *   1) começa por query
 *   2) contém query no nome
 *   3) contém query na alcunha
 *   4) contém query na descrição
 */
export function searchCities(query, limit = 30) {
    const q = _stripAccents(query).trim();
    if (!q) {
        // sem query: devolve cidades mais "populares" primeiro
        const POPULAR = ["lisboa", "porto", "braga", "coimbra", "faro", "funchal", "ponta-delgada", "aveiro",
                          "guimaraes", "evora", "setubal", "viseu", "vila-real", "leiria", "viana-do-castelo"];
        const head = POPULAR.map(id => PT_CITIES.find(c => c.id === id)).filter(Boolean);
        const rest = PT_CITIES.filter(c => !POPULAR.includes(c.id));
        return [...head, ...rest].slice(0, limit);
    }
    const scored = [];
    for (const city of PT_CITIES) {
        const name = _stripAccents(city.name);
        const nick = _stripAccents(city.nickname || "");
        const desc = _stripAccents(city.description || "");
        const district = _stripAccents(city.district || "");
        let score = 0;
        if (name.startsWith(q))            score = 100;
        else if (name.includes(q))         score = 80;
        else if (district.startsWith(q))   score = 60;
        else if (nick.includes(q))         score = 40;
        else if (district.includes(q))     score = 30;
        else if (desc.includes(q))         score = 15;
        else continue;
        // bonus: shorter names rank higher when score equals
        score -= Math.min(20, name.length) * 0.1;
        scored.push({ city, score });
    }
    scored.sort((a, b) => b.score - a.score);
    return scored.slice(0, limit).map(s => s.city);
}

export function getCityById(id) {
    if (!id) return null;
    return PT_CITIES.find(c => c.id === id) || null;
}

export function getCityByName(name) {
    if (!name) return null;
    const target = _stripAccents(name);
    return PT_CITIES.find(c => _stripAccents(c.name) === target) || null;
}
